# モデル
model = "gpt-6.1-sol"
# デフォルト
model_reasoning_effort = "high"
# planモード
plan_mode_reasoning_effort = "xhigh"

web_search = 'live'
personality = "pragmatic"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

notify = ["/Users/m-watanabe/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended", "--previous-notify", "[\"bash\",\"-lc\",\"afplay \\/System\\/Library\\/Sounds\\/Ping.aiff\"]"]
service_tier = "default"

[tui]
status_line = ["model-with-reasoning", "git-branch", "context-used", "current-dir", "approval-mode", "codex-version"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
"gpt-6.1-sol" = 1

[mcp_servers.chrome-devtools]
command = "/Users/m-watanabe/.asdf/shims/npx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.chrome-devtools.env]
ASDF_NODEJS_VERSION = "22.16.0"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[features]
# stable
multi_agent = true
goals = true
terminal_resize_reflow = true
js_repl = false

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."notion@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[apps.asdk_app_69c18c28f1188191bf5b8445c4ab0a2e.tools."notion.notion-update-page"]
approval_mode = "approve"
