# モデル
model = "gpt-5.4"
# 推論
model_reasoning_effort = "high"
# hide_agent_reasoning = true

# Notify（Claude Hooks相当）で音を鳴らす
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

web_search = 'live'
personality = "pragmatic"

[tui]
status_line = ["model-with-reasoning", "project-root", "git-branch", "context-used"]

[mcp_servers.chrome-devtools]
# TODO: これ、なんか良い感じにしたいな…… PCごとにユーザー名違うよね
command = "/Users/m-watanabe/.asdf/shims/npx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.chrome-devtools.env]
ASDF_NODEJS_VERSION = "22.16.0"

[features]
multi_agent = true
